//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Web.SuccessTexts", typeof(SuccessTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire retaken.
        /// </summary>
        public static string ApplicableRegulationsQuestionnaireRetaken {
            get {
                return ResourceManager.GetString("ApplicableRegulationsQuestionnaireRetaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire started.
        /// </summary>
        public static string ApplicableRegulationsQuestionnaireStarted {
            get {
                return ResourceManager.GetString("ApplicableRegulationsQuestionnaireStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire stopped.
        /// </summary>
        public static string ApplicableRegulationsQuestionnaireStopped {
            get {
                return ResourceManager.GetString("ApplicableRegulationsQuestionnaireStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment added.
        /// </summary>
        public static string AssignmentAdded {
            get {
                return ResourceManager.GetString("AssignmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment edited.
        /// </summary>
        public static string AssignmentEdited {
            get {
                return ResourceManager.GetString("AssignmentEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate added.
        /// </summary>
        public static string CandidateAdded {
            get {
                return ResourceManager.GetString("CandidateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate edited.
        /// </summary>
        public static string CandidateEdited {
            get {
                return ResourceManager.GetString("CandidateEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image deleted.
        /// </summary>
        public static string CandidateImageDeleted {
            get {
                return ResourceManager.GetString("CandidateImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded.
        /// </summary>
        public static string CandidateImageUploaded {
            get {
                return ResourceManager.GetString("CandidateImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate deleted.
        /// </summary>
        public static string CandidateRemoved {
            get {
                return ResourceManager.GetString("CandidateRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote added.
        /// </summary>
        public static string CandidateVoteAdded {
            get {
                return ResourceManager.GetString("CandidateVoteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical need edited.
        /// </summary>
        public static string ClinicalNeedEdited {
            get {
                return ResourceManager.GetString("ClinicalNeedEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment added.
        /// </summary>
        public static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment deleted.
        /// </summary>
        public static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment edited.
        /// </summary>
        public static string CommentEdited {
            get {
                return ResourceManager.GetString("CommentEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire retaken.
        /// </summary>
        public static string DeviceClassificationRetaken {
            get {
                return ResourceManager.GetString("DeviceClassificationRetaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire started.
        /// </summary>
        public static string DeviceClassificationStarted {
            get {
                return ResourceManager.GetString("DeviceClassificationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO standard added.
        /// </summary>
        public static string IsoStandardAdded {
            get {
                return ResourceManager.GetString("IsoStandardAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO standard marked as compliant.
        /// </summary>
        public static string IsoStandardMarkedAsCompliant {
            get {
                return ResourceManager.GetString("IsoStandardMarkedAsCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO standard marked as non-compliant.
        /// </summary>
        public static string IsoStandardMarkedAsNonCompliant {
            get {
                return ResourceManager.GetString("IsoStandardMarkedAsNonCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO standard removed.
        /// </summary>
        public static string IsoStandardRemoved {
            get {
                return ResourceManager.GetString("IsoStandardRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left project successfully.
        /// </summary>
        public static string LeftFromProject {
            get {
                return ResourceManager.GetString("LeftFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile changed.
        /// </summary>
        public static string ProfileEdited {
            get {
                return ResourceManager.GetString("ProfileEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded.
        /// </summary>
        public static string ProfilePictureUploaded {
            get {
                return ResourceManager.GetString("ProfilePictureUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created.
        /// </summary>
        public static string ProjectCreated {
            get {
                return ResourceManager.GetString("ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project deleted.
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image deleted.
        /// </summary>
        public static string ProjectImageDeleted {
            get {
                return ResourceManager.GetString("ProjectImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded.
        /// </summary>
        public static string ProjectImageUploaded {
            get {
                return ResourceManager.GetString("ProjectImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation accepted.
        /// </summary>
        public static string ProjectInvitationAccepted {
            get {
                return ResourceManager.GetString("ProjectInvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation declined.
        /// </summary>
        public static string ProjectInvitationDeclined {
            get {
                return ResourceManager.GetString("ProjectInvitationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project leader promoted.
        /// </summary>
        public static string ProjectLeaderPromoted {
            get {
                return ResourceManager.GetString("ProjectLeaderPromoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent.
        /// </summary>
        public static string ProjectMemberInvited {
            get {
                return ResourceManager.GetString("ProjectMemberInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member removed.
        /// </summary>
        public static string ProjectMemberRemoved {
            get {
                return ResourceManager.GetString("ProjectMemberRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation accepted.
        /// </summary>
        public static string ProjectMentorInvitationAccepted {
            get {
                return ResourceManager.GetString("ProjectMentorInvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation declined.
        /// </summary>
        public static string ProjectMentorInvitationDeclined {
            get {
                return ResourceManager.GetString("ProjectMentorInvitationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent.
        /// </summary>
        public static string ProjectMentorInvited {
            get {
                return ResourceManager.GetString("ProjectMentorInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor removed.
        /// </summary>
        public static string ProjectMentorRemoved {
            get {
                return ResourceManager.GetString("ProjectMentorRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project edited.
        /// </summary>
        public static string ProjectTitleAndDescriptionUpdated {
            get {
                return ResourceManager.GetString("ProjectTitleAndDescriptionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string ProjectUpdated {
            get {
                return ResourceManager.GetString("ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File added.
        /// </summary>
        public static string RepositoryFileAdded {
            get {
                return ResourceManager.GetString("RepositoryFileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted.
        /// </summary>
        public static string RepositoryFileHidden {
            get {
                return ResourceManager.GetString("RepositoryFileHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File updated.
        /// </summary>
        public static string RepositoryFileUpdated {
            get {
                return ResourceManager.GetString("RepositoryFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted.
        /// </summary>
        public static string RequestToJoinProjectAccepted {
            get {
                return ResourceManager.GetString("RequestToJoinProjectAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request declined.
        /// </summary>
        public static string RequestToJoinProjectDeclined {
            get {
                return ResourceManager.GetString("RequestToJoinProjectDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent.
        /// </summary>
        public static string RequestToJoinProjectSent {
            get {
                return ResourceManager.GetString("RequestToJoinProjectSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource category created.
        /// </summary>
        public static string ResourceCategoryCreated {
            get {
                return ResourceManager.GetString("ResourceCategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource category deleted.
        /// </summary>
        public static string ResourceCategoryDeleted {
            get {
                return ResourceManager.GetString("ResourceCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource category edited.
        /// </summary>
        public static string ResourceCategoryEdited {
            get {
                return ResourceManager.GetString("ResourceCategoryEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource page created.
        /// </summary>
        public static string ResourcePageCreated {
            get {
                return ResourceManager.GetString("ResourcePageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resoure page deleted.
        /// </summary>
        public static string ResourcePageDeleted {
            get {
                return ResourceManager.GetString("ResourcePageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource page edited.
        /// </summary>
        public static string ResourcePageEdited {
            get {
                return ResourceManager.GetString("ResourcePageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP1 reopened.
        /// </summary>
        public static string WP1Reopened {
            get {
                return ResourceManager.GetString("WP1Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested mentoring.
        /// </summary>
        public static string WP1RequestedMentoring {
            get {
                return ResourceManager.GetString("WP1RequestedMentoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP1 reviewed.
        /// </summary>
        public static string WP1ReviewAccepted {
            get {
                return ResourceManager.GetString("WP1ReviewAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP1 reviewed.
        /// </summary>
        public static string WP1ReviewRejected {
            get {
                return ResourceManager.GetString("WP1ReviewRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP1StepEdited {
            get {
                return ResourceManager.GetString("WP1StepEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP1 submitted for review.
        /// </summary>
        public static string WP1SubmittedForReview {
            get {
                return ResourceManager.GetString("WP1SubmittedForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP2StepEdited {
            get {
                return ResourceManager.GetString("WP2StepEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP3 and WP4 opened successfully.
        /// </summary>
        public static string WP3AndWP4Opened {
            get {
                return ResourceManager.GetString("WP3AndWP4Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP3HealthTechnologySpecificationsEdited {
            get {
                return ResourceManager.GetString("WP3HealthTechnologySpecificationsEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP3 opened successfully.
        /// </summary>
        public static string WP3Opened {
            get {
                return ResourceManager.GetString("WP3Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP3StepEdited {
            get {
                return ResourceManager.GetString("WP3StepEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP3UserAndEnvironmentEdited {
            get {
                return ResourceManager.GetString("WP3UserAndEnvironmentEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP4HealthTechnologySpecificationsEdited {
            get {
                return ResourceManager.GetString("WP4HealthTechnologySpecificationsEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP4StepEdited {
            get {
                return ResourceManager.GetString("WP4StepEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string WP4UserAndEnvironmentEdited {
            get {
                return ResourceManager.GetString("WP4UserAndEnvironmentEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work package unlocked.
        /// </summary>
        public static string WPUnlocked {
            get {
                return ResourceManager.GetString("WPUnlocked", resourceCulture);
            }
        }
    }
}
