//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Projects.Workpackages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Placeholders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Placeholders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Projects.Workpackages.Placeholders", typeof(Placeholders).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can provide any additional information that you think is appropriate. For example, any preliminary studies that you have already performed or reference to similar/ competitor devices.
        ///
        ///Other interesting information includes:
        ///
        ///Any cost estimation; 
        ///industrial process identification; 
        ///animal model for testing that may be representative;
        ///simulations on dummies or SW that may be representative;
        ///if the device is intended to be single use;.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe what are the devices or therapies on the market; if possible, list some pros and cons of the existing solutions.
        ///
        ///Example: list medical, surgical or technical solutions available; define the criteria to choose amongst the have different options. Comment on residual side effects or contraindications that may be improved.
        ///
        ///Worked example: congenital club foot is usually treated by braces (mild cases) or surgery. Both solutions require long healing times and frequent specialistic f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionOfExistingSolutionsAndAnalysis {
            get {
                return ResourceManager.GetString("DescriptionOfExistingSolutionsAndAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe the clinical need that is the target of your device. 
        ///Example 1: write the common or technical name of the pathology, describe the main symptoms and if it is acute/chronic.
        ///Example 2: write the common or technical name of the handicap, describe if it is innate or caused by incidents or a consequence of a pathology
        ///Example 3: describe what is the patient need in terms of cost / improvement of life conditions / improvement of wellbeing
        ///
        ///Worked example 1: Down sindrome is a sindro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionOfNeeds {
            get {
                return ResourceManager.GetString("DescriptionOfNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe how many patients you suppose would need your device, and give description of their state of health and any subgroups.
        ///
        ///Example 1: evaluate how many patients are registered for the target pathology in your country/ worldwide and comment any differences.
        ///
        ///Worked example 1: neonatal hypothermia affects xxx% of preterm children and xx% of babies at term. This means an estimate of xxx babies per year worldwide.
        ///
        ///Example 2: evaluate how the current patient population may evolve ove [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PatientPopulationStudy {
            get {
                return ResourceManager.GetString("PatientPopulationStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should briefly describe your device and how it works. Describe how your product will meet and solve the clinical need.
        ///
        ///Example 1: describe how the device interacts with the human body and why this interaction is beneficial.
        ///
        ///Worked example 1: the syringe allows to deliver liquid substances, for example drugs, to the peripheral blood stream of the patient by piercing the vein walls without laceration
        ///
        ///Example 2: describe which clinical parameter is measures/ altered/ affected by the device
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductFunctionality {
            get {
                return ResourceManager.GetString("ProductFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe the main working parameters of your device and why they are significant to describe its interaction with the patient.
        ///
        ///example 1: describe the time of use, kind of interaction with the human body, forces involved
        ///
        ///worked example 1: the haemodialysis machine allows transferring the blood from the patient body to a filter, by plastic tubings. The blood is circulated in low pressure by a peristaltic pump for some hours and continuously recirculated to the patient.
        ///
        ///worked example [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductPerformance {
            get {
                return ResourceManager.GetString("ProductPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe the main risks that your device may pose to the patient, to the users and bystanders and to the general environment. Propose solutions if you are aware of them.
        ///
        ///Example 1: evaluate electrical and mechanical safety of the device 
        ///
        ///Worked example 1: haemodialysis machine is powered by electricity, there is a risk of electrocution of the patient and operator if it is not well insulated. In the same machine, the roller pump may hurt the operator hands if it is touched while it is r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductSafety {
            get {
                return ResourceManager.GetString("ProductSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe who will use the device and if they need special training.
        ///
        ///Example 1: define the professional profile of the end user
        ///
        ///Worked example 1: a hip implant can be implanted in the patient only by a surgery team; all components of the surgery team are medical professional and at least one specialized orthopedic surgeon shall be responsible of the surgery
        ///
        ///Worked example 2: a thermometer is used by any adult or teenager with normal cognitive and bodily abilities; young children or p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductUsability {
            get {
                return ResourceManager.GetString("ProductUsability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you should describe what your end user prefers or needs; this may be the same or different than the patient need and relates more to &quot;easy and friendly to use&quot; that to patient state of health.
        ///
        ///Example: describe if the device should be lightweight to be portable; describe the sounds and colors that are expected; describe handling and visual requirements
        ///
        ///Worked example 1: a defibrillator for use in airports and other meeting places should be very intuitive to use and should give vocal commands in t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserRequirementStudy {
            get {
                return ResourceManager.GetString("UserRequirementStudy", resourceCulture);
            }
        }
    }
}
