//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Questionnaires.ApplicableRegulations.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Questionnaires.ApplicableRegulations.Texts.QuestionTexts", typeof(QuestionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device “implantable” and “not active”?.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device “active” and its source of energy is electrical?.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device a software or does it contain software (applies also to firmware)?.
        /// </summary>
        public static string q2_1 {
            get {
                return ResourceManager.GetString("q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the device containing software intended to be part of a IT-network?.
        /// </summary>
        public static string q2_1_1 {
            get {
                return ResourceManager.GetString("q2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device “implantable” and “active”?.
        /// </summary>
        public static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device intended to be sterile?.
        /// </summary>
        public static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be terminally sterilized?.
        /// </summary>
        public static string q4_1 {
            get {
                return ResourceManager.GetString("q4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Will it be terminally sterilized) by Ethilene Oxide?.
        /// </summary>
        public static string q4_1_1 {
            get {
                return ResourceManager.GetString("q4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Will it be terminally sterilized) by Irradiation?.
        /// </summary>
        public static string q4_1_2 {
            get {
                return ResourceManager.GetString("q4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Will it be terminally sterilized) by moist heat, steam?.
        /// </summary>
        public static string q4_1_3 {
            get {
                return ResourceManager.GetString("q4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Will it be terminally sterilized) by dry heat?.
        /// </summary>
        public static string q4_1_4 {
            get {
                return ResourceManager.GetString("q4_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be sterilized in process?.
        /// </summary>
        public static string q4_2 {
            get {
                return ResourceManager.GetString("q4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your device come in contact to the human body (any kind of contact, brief or permanent, in any location of the human body)?.
        /// </summary>
        public static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your device contain substances of animal origin?.
        /// </summary>
        public static string q5_1 {
            get {
                return ResourceManager.GetString("q5_1", resourceCulture);
            }
        }
    }
}
