version: '3'

services:
  ubora.web:
    build: ./Ubora.Web/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      FunctionalTesting: "DisabledWebPack"
      ConnectionStrings__ApplicationDbConnection: "server=postgres;Port=5432;userid=postgres;password=ubora;database=ubora"
    ports:
      - "5000:80"
    depends_on:
      - "postgres"
    networks:
      - ubora-testnetwork

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: ubora
      POSTGRES_DB: ubora
    networks:
      - ubora-testnetwork
  
  functional.tests:
    build: ./Ubora.Web.FunctionalTests/
    volumes:
      - ./Ubora.Web.FunctionalTests:/app
      - /app/node_modules
    depends_on:
      - "ubora.web"
      - "selenium"
    command: /bin/bash -c "./wait-for-it.sh ubora.web:80 -t 30 && npm test -- --host selenium"
    networks:
      - ubora-testnetwork

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"  
    networks:
      - ubora-testnetwork

networks:
  ubora-testnetwork:
    driver: bridge