version: '3'

services:
  ci-build:  
    image: microsoft/dotnet:2.1.301-sdk
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - marten_testing_database=server=postgres;Port=5432;userid=postgres;password=ubora;database=ubora
    depends_on:
      - "postgres"
    networks:
      - ubora-testnetwork
    command: ./RunCIBuild.sh

  postgres:
    container_name: 'postgresubora'
    image: postgres
    environment:
      POSTGRES_PASSWORD: ubora
      POSTGRES_DB: ubora
    networks:
      - ubora-testnetwork

networks:
  ubora-testnetwork:
    driver: bridge

    