version: '3.4'

services:
  ci-build:  
    image: microsoft/aspnetcore-build:2.0.6-2.1.101
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - marten_testing_database=server=postgres;Port=5432;userid=postgres;password=ubora;database=ubora
    depends_on:
      - "postgres"
    networks:
      - ubora-testnetwork
    command: ./RunCIBuild.sh

  postgres:
    container_name: 'postgresubora'
    image: postgres
    environment:
      POSTGRES_PASSWORD: ubora
      POSTGRES_DB: ubora
    networks:
      - ubora-testnetwork

networks:
  ubora-testnetwork:
    driver: bridge

    