version: '3'

services:
  ubora.web:
    build: ./Ubora.Web/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__ApplicationDbConnection: "server=postgres;Port=5432;userid=postgres;password=ubora;database=ubora"
      Pandoc__Address: "ubora.pandoc"
      Pandoc__Port: 1337
      Pandoc__Key: "testapikey"
    depends_on:
      - "postgres"
      - "ubora.pandoc"
    networks:
      - ubora-testnetwork

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: ubora
      POSTGRES_DB: ubora
    networks:
      - ubora-testnetwork

  ubora.pandoc:
    build: ./Ubora.UniversalDocumentConverter
    environment:
      CONVERTER_API_KEY: "testapikey"
    volumes:
      - ./Ubora.UniversalDocumentConverter:/app
      - /app/node_modules
    networks:
      - ubora-testnetwork
  
  functional.tests:
    build: ./Ubora.Web.FunctionalTests/
    volumes:
      - ./Ubora.Web.FunctionalTests:/app
      - /app/node_modules
    depends_on:
      - "ubora.web"
      - "selenium"
    command: /bin/bash -c "npm i --silent && ./wait-for-it.sh ubora.web:80 -t 30 && npm test -- --host selenium"
    networks:
      - ubora-testnetwork

  selenium:
    image: selenium/standalone-chrome
    networks:
      - ubora-testnetwork

networks:
  ubora-testnetwork:
    driver: bridge