version: '3'

services:
  ubora.web:
    container_name: 'ubora.web'
    image: martinbetlem/ubora-web:3
    environment:
      Pandoc__Ip: "ubora.pandoc"
      Pandoc__Url: "http://ubora.pandoc:1337"
      Pandoc__Key: "testapikey"
    depends_on:
      - "ubora.pandoc"
    networks:
      - ubora-network      

  ubora.pandoc:
    container_name: 'ubora.pandoc'
    image: ubora/pandoc:latest
    environment:
      CONVERTER_API_KEY: "testapikey"
    volumes:
      - ./Ubora.UniversalDocumentConverter:/app
      - /app/node_modules
    networks:
      - ubora-network

networks:
  ubora-network:
    driver: bridge

volumes:
  psqlvolumes:
    driver: local