version: '3'

services:
  ubora.web:
    build: 
      context: ./
      dockerfile: Ubora.Web/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - postgres
    command: /bin/bash -c "./wait-for-it.sh postgres:5432 && dotnet Ubora.Web.dll"

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD: ubora
      POSTGRES_DB: ubora
  
  functional.tests:
    build: 
      context: ./
      dockerfile: Ubora.Web.FunctionalTests/Dockerfile
    command: /bin/bash -c "./wait-for-it.sh ubora.web:80 && cd Ubora.Web.FunctionalTests && npm test -- --host selenium"
    depends_on:
      - ubora.web

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"  
    depends_on:
      - ubora.web