//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Questionnaires.DeviceClassifications.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnswerTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnswerTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Questionnaires.DeviceClassifications.Texts.AnswerTexts", typeof(AnswerTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-invasive.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasive.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-surgically invasive (this means that it enters in the human body but only through a body orifice and without piercing or cutting the skin or membranes)?.
        /// </summary>
        public static string q2_1 {
            get {
                return ResourceManager.GetString("q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_1_2 {
            get {
                return ResourceManager.GetString("q2_1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_1_3 {
            get {
                return ResourceManager.GetString("q2_1_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity and it is NOT liable to be absorbed by the mucous membrane..
        /// </summary>
        public static string q2_1_1_4 {
            get {
                return ResourceManager.GetString("q2_1_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but IT IS liable to be absorbed by the mucous membrane..
        /// </summary>
        public static string q2_1_1_5 {
            get {
                return ResourceManager.GetString("q2_1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_1_6 {
            get {
                return ResourceManager.GetString("q2_1_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class I active medical device.
        /// </summary>
        public static string q2_1_2 {
            get {
                return ResourceManager.GetString("q2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_2_2 {
            get {
                return ResourceManager.GetString("q2_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_2_3 {
            get {
                return ResourceManager.GetString("q2_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but it is NOT liable to be absorbed by the mucous membrane..
        /// </summary>
        public static string q2_1_2_4 {
            get {
                return ResourceManager.GetString("q2_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but IT IS liable to be absorbed by the mucous membrane..
        /// </summary>
        public static string q2_1_2_5 {
            get {
                return ResourceManager.GetString("q2_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity..
        /// </summary>
        public static string q2_1_2_6 {
            get {
                return ResourceManager.GetString("q2_1_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class IIa or higher class active medical device.
        /// </summary>
        public static string q2_1_3 {
            get {
                return ResourceManager.GetString("q2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgically invasive.
        /// </summary>
        public static string q2_2 {
            get {
                return ResourceManager.GetString("q2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient (less than 60 minutes).
        /// </summary>
        public static string q2_2_1 {
            get {
                return ResourceManager.GetString("q2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short term (from 60 minutes to 30 days).
        /// </summary>
        public static string q2_2_2 {
            get {
                return ResourceManager.GetString("q2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the teeth.
        /// </summary>
        public static string q2_2_2_5_1 {
            get {
                return ResourceManager.GetString("q2_2_2_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In any part of the body other than the teeth.
        /// </summary>
        public static string q2_2_2_5_2 {
            get {
                return ResourceManager.GetString("q2_2_2_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implantable or long term (more than 30 days).
        /// </summary>
        public static string q2_2_3 {
            get {
                return ResourceManager.GetString("q2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the teeth.
        /// </summary>
        public static string q2_2_3_4_1 {
            get {
                return ResourceManager.GetString("q2_2_3_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In any part of the body other than the teeth.
        /// </summary>
        public static string q2_2_3_4_2 {
            get {
                return ResourceManager.GetString("q2_2_3_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in a potentially hazardous way (consider nature of energy, density of energy, site of the body)..
        /// </summary>
        public static string q3_1_1 {
            get {
                return ResourceManager.GetString("q3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in a NON-hazardous way..
        /// </summary>
        public static string q3_1_2 {
            get {
                return ResourceManager.GetString("q3_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, an impact that may cause death or an irreversible deterioration of a person&apos;s state of health..
        /// </summary>
        public static string q3_5_1_1 {
            get {
                return ResourceManager.GetString("q3_5_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, an impact that may cause a serious deterioration of a person&apos;s state of health or a surgical intervention..
        /// </summary>
        public static string q3_5_1_2 {
            get {
                return ResourceManager.GetString("q3_5_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, it monitors vital physiological parameters, where the nature of variations of those parameters is such that it could result in immediate danger to the patient..
        /// </summary>
        public static string q3_5_2_1 {
            get {
                return ResourceManager.GetString("q3_5_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, it monitors non-vital physiological parameters, so that the nature of variations of those parameters is such that it could never and in no cases result in immediate danger to the patient..
        /// </summary>
        public static string q3_5_2_2 {
            get {
                return ResourceManager.GetString("q3_5_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High or medium.
        /// </summary>
        public static string q9_1 {
            get {
                return ResourceManager.GetString("q9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string q9_2 {
            get {
                return ResourceManager.GetString("q9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negliglible.
        /// </summary>
        public static string q9_3 {
            get {
                return ResourceManager.GetString("q9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
