//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Questionnaires.DeviceClassifications.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnswerTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnswerTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Questionnaires.DeviceClassifications.Texts.AnswerTexts", typeof(AnswerTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON-INVASIVE.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVASIVE.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it NON-SURGICALLY INVASIVE (this means that it enters in the human body but only through a body orifice and without piercing or cutting the skin or membranes)?.
        /// </summary>
        public static string q2_1 {
            get {
                return ResourceManager.GetString("q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for transient use?.
        /// </summary>
        public static string q2_1_1_1 {
            get {
                return ResourceManager.GetString("q2_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for short-term use  only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_1_2 {
            get {
                return ResourceManager.GetString("q2_1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for short-term use in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_1_3 {
            get {
                return ResourceManager.GetString("q2_1_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity and it not liable to be absorbed by the mucous membrane?.
        /// </summary>
        public static string q2_1_1_4 {
            get {
                return ResourceManager.GetString("q2_1_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but it is liable to be absorbed by the mucous membrane?.
        /// </summary>
        public static string q2_1_1_5 {
            get {
                return ResourceManager.GetString("q2_1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_1_6 {
            get {
                return ResourceManager.GetString("q2_1_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for connection to a class I active medical device?.
        /// </summary>
        public static string q2_1_2 {
            get {
                return ResourceManager.GetString("q2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for connection to a class IIa or higher class active medical device?.
        /// </summary>
        public static string q2_1_3 {
            get {
                return ResourceManager.GetString("q2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it SURGICALLY INVASIVE?.
        /// </summary>
        public static string q2_2 {
            get {
                return ResourceManager.GetString("q2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it for TRANSIENT use?.
        /// </summary>
        public static string q2_2_1 {
            get {
                return ResourceManager.GetString("q2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it for SHORT TERM use?.
        /// </summary>
        public static string q2_2_2 {
            get {
                return ResourceManager.GetString("q2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it in the teeth?.
        /// </summary>
        public static string q2_2_2_5_1 {
            get {
                return ResourceManager.GetString("q2_2_2_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it in any part of the body other than the teeth?.
        /// </summary>
        public static string q2_2_2_5_2 {
            get {
                return ResourceManager.GetString("q2_2_2_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it implantable or LONG TERM use?.
        /// </summary>
        public static string q2_2_3 {
            get {
                return ResourceManager.GetString("q2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it in the teeth?.
        /// </summary>
        public static string q2_2_3_4_1 {
            get {
                return ResourceManager.GetString("q2_2_3_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it in any part of the body other than the teeth?.
        /// </summary>
        public static string q2_2_3_4_2 {
            get {
                return ResourceManager.GetString("q2_2_3_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it administer energy to or exchange energy with the human body in a potentially hazardous way (consider nature of energy, density of energy, site of the body)?.
        /// </summary>
        public static string q3_1_1 {
            get {
                return ResourceManager.GetString("q3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it administer energy to or exchange energy with the human body in a NON-hazardous way?.
        /// </summary>
        public static string q3_1_2 {
            get {
                return ResourceManager.GetString("q3_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does such decision have an impact that may cause death or an irreversible deterioration of a person&apos;s state of health?.
        /// </summary>
        public static string q3_5_1_1 {
            get {
                return ResourceManager.GetString("q3_5_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does such decision have an impact that may cause a serious deterioration of a person&apos;s state of health or a surgical intervention?.
        /// </summary>
        public static string q3_5_1_2 {
            get {
                return ResourceManager.GetString("q3_5_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it monitor vital physiological parameters, where the nature of variations of those parameters is such that it could result in immediate danger to the patient?.
        /// </summary>
        public static string q3_5_2_1 {
            get {
                return ResourceManager.GetString("q3_5_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it monitor non-vital physiological parameters, so that the nature of variations of those parameters is such that it could never and in no cases result in immediate danger to the patient?.
        /// </summary>
        public static string q3_5_2_2 {
            get {
                return ResourceManager.GetString("q3_5_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it present a high or medium potential for internal exposure?.
        /// </summary>
        public static string q9_1 {
            get {
                return ResourceManager.GetString("q9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it present a low potential for internal exposure?.
        /// </summary>
        public static string q9_2 {
            get {
                return ResourceManager.GetString("q9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it present a negliglible potential for internal exposure?.
        /// </summary>
        public static string q9_3 {
            get {
                return ResourceManager.GetString("q9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
