//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Questionnaires.DeviceClassifications.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NoteTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoteTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Questionnaires.DeviceClassifications.Texts.NoteTexts", typeof(NoteTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Invasive device’ means any device which, in whole or in part, penetrates inside the body, either through a body orifice or through the surface of the body; for example: a hip implant, a pacemaker, a catheter, a needle, an endotracheal tube..
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Biological effect&apos; - All materials and devices have the potential to affect tissues following use in a surgically invasive procedure. A material is considered to have a biological effect if it actively and intentionally induces, alters or prevents a response from the tissues that is mediated by specific reactions at a molecular level. Such a device may be described as bioactive.
        ///&lt;p&gt;
        ///&apos;Wholly or mainly absorbed&apos; - The term absorption refers to the degradation of a material within the body and the metabolic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q2_2_1_5 {
            get {
                return ResourceManager.GetString("q2_2_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Biological effect&apos; - All materials and devices have the potential to affect tissues following use in a surgically invasive procedure. A material is considered to have a biological effect if it actively and intentionally induces, alters or prevents a response from the tissues that is mediated by specific reactions at a molecular level. Such a device may be described as bioactive.
        ///&lt;p&gt;
        ///&apos;Wholly or mainly absorbed&apos; - The term absorption refers to the degradation of a material within the body and the metabolic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q2_2_2_4 {
            get {
                return ResourceManager.GetString("q2_2_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Active device’ means any device, the operation of which depends on a source of energy other than that generated by the human body for that purpose, or by gravity, and which acts by changing the density of or converting that energy. Devices intended to transmit energy, substances or other elements between an active device and the patient, without any significant change, shall not be deemed to be active devices. Software shall also be deemed to be an active device.
        ///&lt;p&gt;
        ///‘Active therapeutic device’ means any [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Active therapeutic device’ means any active device used, whether alone or in combination with other devices, to support, modify, replace or restore biological functions or structures with a view to treatment or alleviation of an illness, injury or disability. 
        ///&lt;p&gt;Source: Regulation EU 2017/745&lt;/p&gt;.
        /// </summary>
        internal static string q3_1 {
            get {
                return ResourceManager.GetString("q3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Active therapeutic device’ means any active device used, whether alone or in combination with other devices, to support, modify, replace or restore biological functions or structures with a view to treatment or alleviation of an illness, injury or disability. Source: Regulation EU 2017/745
        ///&lt;p&gt;
        ///Some examples of active therapeutic class IIb devices that may be controlled or monitored include:
        ///&lt;/p&gt;
        ///&lt;ul class=&quot;mb-3&quot;&gt;
        ///&lt;li&gt;Kinetic energy&lt;/li&gt;
        ///&lt;li&gt;Lung ventilators&lt;/li&gt;
        ///&lt;li&gt;Thermal energy&lt;/li&gt;
        ///&lt;li&gt;Incubato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q3_2 {
            get {
                return ResourceManager.GetString("q3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Active device’ means any device, the operation of which depends on a source of energy other than that generated by the human body for that purpose, or by gravity, and which acts by changing the density of or converting that energy. Devices intended to transmit energy, substances or other elements between an active device and the patient, without any significant change, shall not be deemed to be active devices. Software shall also be deemed to be an active device. Source: Regulation EU 2017/745
        ///&lt;p&gt;
        ///Exampl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q3_3 {
            get {
                return ResourceManager.GetString("q3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:
        ///&lt;ul class=&quot;mb-3&quot;&gt;
        ///&lt;li&gt;Magnetic resonance equipment&lt;/li&gt;
        ///&lt;li&gt;Pulp testers&lt;/li&gt;
        ///&lt;li&gt;Evoked response stimulators&lt;/li&gt;
        ///&lt;li&gt;Diagnostic ultrasound&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;Source: MEDDEV 2.4/1 rev 9&lt;/p&gt;
        ///.
        /// </summary>
        internal static string q3_4_1 {
            get {
                return ResourceManager.GetString("q3_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital physiological processes and parameters include, for example respiration, heart rate, cerebral functions, blood gases, blood pressure and body temperature. Medical devices intended to be used for continuous surveillance of vital physiological processes in anaesthesia, intensive care or emergency care are in Class IIb, whilst medical devices intended to be used to obtain readings of vital physiological signals in routine check ups and in self-monitoring are in Class IIa. A thermal imaging device intende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q3_4_2 {
            get {
                return ResourceManager.GetString("q3_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is usually the case in intensive care units, source Meddev 2.4/1 rev 9 explains:
        ///&lt;p&gt;
        ///Vital physiological processes and parameters include, for example respiration, heart rate, cerebral functions, blood gases, blood pressure and body temperature. Medical devices intended to be used for continuous surveillance of vital physiological processes in anaesthesia, intensive care or emergency care are in Class IIb, whilst medical devices intended to be used to obtain readings of vital physiological signals in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q3_4_2_1 {
            get {
                return ResourceManager.GetString("q3_4_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Nanomaterial’ means a natural, incidental or manufactured material containing particles in an unbound state or as an aggregate or as an agglomerate and where, for 50 % or more of the particles in the number size distribution, one or more external dimensions is in the size range 1-100 nm; Fullerenes, graphene flakes and single-wall carbon nanotubes with one or more external dimensions below 1 nm shall also be deemed to be nanomaterials. 
        ///&lt;p&gt;Source: Regulation EU 2017/745&lt;/p&gt;.
        /// </summary>
        internal static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
    }
}
