//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.Questionnaires.DeviceClassifications.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.Questionnaires.DeviceClassifications.Texts.QuestionTexts", typeof(QuestionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device INVASIVE or NON INVASIVE?.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for channelling or storing blood, body liquids, cells or tissues, liquids or gases for the purpose of eventual infusion, administration or introduction into the body?.
        /// </summary>
        public static string q1_1 {
            get {
                return ResourceManager.GetString("q1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May it be connected to an active medical device in class IIa or a higher class?.
        /// </summary>
        public static string q1_1_1 {
            get {
                return ResourceManager.GetString("q1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for use for storing or channelling blood or other body liquids or for storing organs, parts of organs or body cells and tissues, but it is not a blood bag?.
        /// </summary>
        public static string q1_1_2 {
            get {
                return ResourceManager.GetString("q1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a blood bag?.
        /// </summary>
        public static string q1_1_3 {
            get {
                return ResourceManager.GetString("q1_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for modifying the biological or chemical composition of human tissues or cells, blood, other body liquids or other liquids intended for implantation or administration into the body?.
        /// </summary>
        public static string q1_1_4 {
            get {
                return ResourceManager.GetString("q1_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the treatment consist of filtration, centrifugation or exchanges of gas, heat?.
        /// </summary>
        public static string q1_1_4_1 {
            get {
                return ResourceManager.GetString("q1_1_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the treatment other than filtration, centrifugation or exchanges of gas, heat?.
        /// </summary>
        public static string q1_1_4_2 {
            get {
                return ResourceManager.GetString("q1_1_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device a substance or a mixture of substances intended to be used in vitro in direct contact with human cells, tissues or organs taken off from the human body or with human embryos before their implantation or administration into the body?.
        /// </summary>
        public static string q1_1_4_3 {
            get {
                return ResourceManager.GetString("q1_1_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended come into contact with injured skin or mucous membrane?.
        /// </summary>
        public static string q1_1_5 {
            get {
                return ResourceManager.GetString("q1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to be used as a mechanical barrier, for compression or for absorption of exudates?.
        /// </summary>
        public static string q1_1_5_1 {
            get {
                return ResourceManager.GetString("q1_1_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to be used principally for injuries to skin which have breached the dermis or mucous membrane and can only heal by secondary intent?.
        /// </summary>
        public static string q1_1_5_2 {
            get {
                return ResourceManager.GetString("q1_1_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it principally intended to manage the micro-environment of injured skin or mucous membrane?.
        /// </summary>
        public static string q1_1_5_3 {
            get {
                return ResourceManager.GetString("q1_1_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to administer medicinal products by inhalation, being an invasive device with respect to body orifices, other than surgically invasive devices?.
        /// </summary>
        public static string q10 {
            get {
                return ResourceManager.GetString("q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does its mode of action have an essential impact on the efficacy and safety of the administered medicinal product?.
        /// </summary>
        public static string q10_1 {
            get {
                return ResourceManager.GetString("q10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to treat life-threatening conditions?.
        /// </summary>
        public static string q10_2 {
            get {
                return ResourceManager.GetString("q10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it composed of substances or of combinations of substances that are intended to be introduced into the human body via a body orifice or applied to the skin and that are absorbed by or locally dispersed in the human body?.
        /// </summary>
        public static string q11 {
            get {
                return ResourceManager.GetString("q11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it or it products of metabolism, systemically absorbed by the human body in order to achieve the intended purpose?.
        /// </summary>
        public static string q11_1 {
            get {
                return ResourceManager.GetString("q11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it achieve its intended purpose in the stomach or lower gastrointestinal tract and it, or its products of metabolism, is systemically absorbed by the human body?.
        /// </summary>
        public static string q11_2 {
            get {
                return ResourceManager.GetString("q11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it applied to the skin or is it are applied in the nasal or oral cavity as far as the pharynx, and achieve the intended purpose on those cavities?.
        /// </summary>
        public static string q11_3 {
            get {
                return ResourceManager.GetString("q11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it an active therapeutic device with an integrated or incorporated diagnostic function that includes an integrated or incorporated diagnostic function which significantly determines the patient management by the device (example: closed loop systems or automated external defibrillators)?.
        /// </summary>
        public static string q12 {
            get {
                return ResourceManager.GetString("q12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string q2_1 {
            get {
                return ResourceManager.GetString("q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it NOT intended for connection to any active medical device?.
        /// </summary>
        public static string q2_1_1 {
            get {
                return ResourceManager.GetString("q2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for transient use?.
        /// </summary>
        public static string q2_1_1_1 {
            get {
                return ResourceManager.GetString("q2_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for connection to a class I active medical device?.
        /// </summary>
        public static string q2_1_2 {
            get {
                return ResourceManager.GetString("q2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for transient use?.
        /// </summary>
        public static string q2_1_2_1 {
            get {
                return ResourceManager.GetString("q2_1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for short-term use only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_2_2 {
            get {
                return ResourceManager.GetString("q2_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for short-term use in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_2_3 {
            get {
                return ResourceManager.GetString("q2_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but it is liable to be absorbed by the mucous membrane?.
        /// </summary>
        public static string q2_1_2_4 {
            get {
                return ResourceManager.GetString("q2_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use only in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity but it is liable to be absorbed by the mucous membrane?.
        /// </summary>
        public static string q2_1_2_5 {
            get {
                return ResourceManager.GetString("q2_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for long-term use in any other site than the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in the nasal cavity?.
        /// </summary>
        public static string q2_1_2_6 {
            get {
                return ResourceManager.GetString("q2_1_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string q2_2_1 {
            get {
                return ResourceManager.GetString("q2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically to control, diagnose, monitor or correct a defect of the heart or of the central circulatory system through direct contact with those parts of the body?.
        /// </summary>
        public static string q2_2_1_1 {
            get {
                return ResourceManager.GetString("q2_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a reusable surgical instrument?.
        /// </summary>
        public static string q2_2_1_2 {
            get {
                return ResourceManager.GetString("q2_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically for use in direct contact with the heart or central circulatory system or the central nervous system?.
        /// </summary>
        public static string q2_2_1_3 {
            get {
                return ResourceManager.GetString("q2_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to supply energy in the form of ionizing radiation?.
        /// </summary>
        public static string q2_2_1_4 {
            get {
                return ResourceManager.GetString("q2_2_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to have a biological effect or be wholly or mainly absorbed?.
        /// </summary>
        public static string q2_2_1_5 {
            get {
                return ResourceManager.GetString("q2_2_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to administer medicinal products by means of a delivery system in a manner that is potentially hazardous?.
        /// </summary>
        public static string q2_2_1_6 {
            get {
                return ResourceManager.GetString("q2_2_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically to control, diagnose, monitor or correct a defect of the heart or of the central circulatory system through direct contact with those parts of the body?.
        /// </summary>
        public static string q2_2_2_1 {
            get {
                return ResourceManager.GetString("q2_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically for use in direct contact with the heart or central circulatory system or the central nervous system?.
        /// </summary>
        public static string q2_2_2_2 {
            get {
                return ResourceManager.GetString("q2_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to have a biological effect or are wholly or mainly absorbed?.
        /// </summary>
        public static string q2_2_2_3 {
            get {
                return ResourceManager.GetString("q2_2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to have a biological effect or be wholly or mainly absorbed?.
        /// </summary>
        public static string q2_2_2_4 {
            get {
                return ResourceManager.GetString("q2_2_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to undergo chemical change in the body?.
        /// </summary>
        public static string q2_2_2_5 {
            get {
                return ResourceManager.GetString("q2_2_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to administer medicines?.
        /// </summary>
        public static string q2_2_2_5_3 {
            get {
                return ResourceManager.GetString("q2_2_2_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to be placed in the teeth?.
        /// </summary>
        public static string q2_2_3_1 {
            get {
                return ResourceManager.GetString("q2_2_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it an ancillary component of a total or partial joint replacement such as screws, wedges, plates and instruments?.
        /// </summary>
        public static string q2_2_3_10 {
            get {
                return ResourceManager.GetString("q2_2_3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a spinal disc replacement implant?.
        /// </summary>
        public static string q2_2_3_11 {
            get {
                return ResourceManager.GetString("q2_2_3_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it an implantable device that come into contact with the spinal column?.
        /// </summary>
        public static string q2_2_3_12 {
            get {
                return ResourceManager.GetString("q2_2_3_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it an ancillary component of a spinal disc replacement or other device that comes in contact with the spinal column such as screws, wedges, plates and instruments?.
        /// </summary>
        public static string q2_2_3_13 {
            get {
                return ResourceManager.GetString("q2_2_3_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for use in direct contact with the heart or central circulatory system or the central nervous system?.
        /// </summary>
        public static string q2_2_3_2 {
            get {
                return ResourceManager.GetString("q2_2_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to have a biological effect or be wholly or mainly absorbed?.
        /// </summary>
        public static string q2_2_3_3 {
            get {
                return ResourceManager.GetString("q2_2_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to undergo chemical change in the body?.
        /// </summary>
        public static string q2_2_3_4 {
            get {
                return ResourceManager.GetString("q2_2_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to administer medicines?.
        /// </summary>
        public static string q2_2_3_5 {
            get {
                return ResourceManager.GetString("q2_2_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it an active implantable device or its accessory?.
        /// </summary>
        public static string q2_2_3_6 {
            get {
                return ResourceManager.GetString("q2_2_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a breast implant?.
        /// </summary>
        public static string q2_2_3_7 {
            get {
                return ResourceManager.GetString("q2_2_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a surgical mesh?.
        /// </summary>
        public static string q2_2_3_8 {
            get {
                return ResourceManager.GetString("q2_2_3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a total or partial joint replacement?.
        /// </summary>
        public static string q2_2_3_9 {
            get {
                return ResourceManager.GetString("q2_2_3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your device ACTIVE?.
        /// </summary>
        public static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it therapeutic?.
        /// </summary>
        public static string q3_1 {
            get {
                return ResourceManager.GetString("q3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string q3_1_1 {
            get {
                return ResourceManager.GetString("q3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to emit ionizing radiation?.
        /// </summary>
        public static string q3_1_3 {
            get {
                return ResourceManager.GetString("q3_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for therapeutic radiology, including interventional radiology devices and devices which control or monitor such devices, or which directly influence their performance?.
        /// </summary>
        public static string q3_1_4 {
            get {
                return ResourceManager.GetString("q3_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to control or monitor a device that emits ionizing radiation, or does it directly influence the performance a device that emits ionizing radiation?.
        /// </summary>
        public static string q3_1_5 {
            get {
                return ResourceManager.GetString("q3_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to control or monitor the performance of active therapeutic class IIb devices, or intended directly to influence the performance of such devices?.
        /// </summary>
        public static string q3_2 {
            get {
                return ResourceManager.GetString("q3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for controlling, monitoring or directly influencing the performance of active implantable devices?.
        /// </summary>
        public static string q3_3 {
            get {
                return ResourceManager.GetString("q3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended for diagnosis and monitoring?.
        /// </summary>
        public static string q3_4 {
            get {
                return ResourceManager.GetString("q3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to supply energy which will be absorbed by the human body?.
        /// </summary>
        public static string q3_4_1 {
            get {
                return ResourceManager.GetString("q3_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it only intended to intended to illuminate the patient&apos;s body, in the visible spectrum?.
        /// </summary>
        public static string q3_4_1_1 {
            get {
                return ResourceManager.GetString("q3_4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it supply energy different than light in the visible spectrum?.
        /// </summary>
        public static string q3_4_1_2 {
            get {
                return ResourceManager.GetString("q3_4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to image in vivo distribution of radiopharmaceuticals?.
        /// </summary>
        public static string q3_4_1_3 {
            get {
                return ResourceManager.GetString("q3_4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to allow direct diagnosis or monitoring of vital physiological processes?.
        /// </summary>
        public static string q3_4_2 {
            get {
                return ResourceManager.GetString("q3_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are the vital physiological processes such as the patient may be in immediate danger if the vary (example: variations in cardiac performance, respiration, activity of the central nervous system)?.
        /// </summary>
        public static string q3_4_2_1 {
            get {
                return ResourceManager.GetString("q3_4_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the diagnosis and monitoring done in a clinical situation while the patient is in immediate danger?.
        /// </summary>
        public static string q3_4_2_2 {
            get {
                return ResourceManager.GetString("q3_4_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string q3_4_2_3 {
            get {
                return ResourceManager.GetString("q3_4_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to emit ionizing radiation for diagnostics?.
        /// </summary>
        public static string q3_4_3 {
            get {
                return ResourceManager.GetString("q3_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a software?.
        /// </summary>
        public static string q3_5 {
            get {
                return ResourceManager.GetString("q3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to provide information which is used to take decisions with diagnosis or therapeutic purposes?.
        /// </summary>
        public static string q3_5_1 {
            get {
                return ResourceManager.GetString("q3_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does such decision have an impact that may cause death or an irreversible deterioration of a person&apos;s state of health?.
        /// </summary>
        public static string q3_5_1_1 {
            get {
                return ResourceManager.GetString("q3_5_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to monitor physiological processes?.
        /// </summary>
        public static string q3_5_2 {
            get {
                return ResourceManager.GetString("q3_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it monitor vital physiological parameters, where the nature of variations of those parameters is such that it could result in immediate danger to the patient?.
        /// </summary>
        public static string q3_5_2_1 {
            get {
                return ResourceManager.GetString("q3_5_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended to administer and/or remove medicinal products, body liquids or other substances to or from the body?.
        /// </summary>
        public static string q3_6 {
            get {
                return ResourceManager.GetString("q3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this done in a manner that is potentially hazardous (taking account of the nature of the substances involved, of the part of the body concerned and of the mode of application)?.
        /// </summary>
        public static string q3_6_1 {
            get {
                return ResourceManager.GetString("q3_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your device incorporate a medicinal product with an ancillary function?.
        /// </summary>
        public static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it used for contraception or prevention of the transmission of sexually transmitted diseases?.
        /// </summary>
        public static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it implantable or long term invasive?.
        /// </summary>
        public static string q5_1 {
            get {
                return ResourceManager.GetString("q5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically to be used for disinfecting, cleaning, rinsing or, where appropriate, hydrating contact lenses?.
        /// </summary>
        public static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it intended specifically to be used for disinfecting or sterilising medical devices that are not contact lenses ? NOTE: If it is only intended for cleaning and only by physical action, this rule does not apply..
        /// </summary>
        public static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a disinfecting solution or washer-disinfector, intended specifically to be used for disinfecting invasive devices, as the end point of processing?.
        /// </summary>
        public static string q7_1 {
            get {
                return ResourceManager.GetString("q7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it specifically intended for recording of diagnostic images generated by X-ray radiation?.
        /// </summary>
        public static string q7_3 {
            get {
                return ResourceManager.GetString("q7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it manufactured utilizing tissues or cells of human or animal origin, or their derivatives, which are non-viable or rendered non-viable?.
        /// </summary>
        public static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it incorporate or contain nanomaterials?.
        /// </summary>
        public static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string q9_1 {
            get {
                return ResourceManager.GetString("q9_1", resourceCulture);
            }
        }
    }
}
