//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.ApplicableRegulations.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IsoStandardTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IsoStandardTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.ApplicableRegulations.Texts.IsoStandardTexts", typeof(IsoStandardTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030261816&quot;&gt;EN ISO 14630:2012&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies requirements for all devices that are implanted in the human body but are not active.&lt;/p&gt;
        ///    &lt;p&gt;NOTE: This norm is closely related to &lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030285625&quot;&gt;EN ISO 16061: 2015&lt;/a&gt; that refers to associated instruments.&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;https://webstore.iec.ch/publication/2612&quot;&gt;IEC 60601-1:2005+AMD1:2012 CSV (consolidated version)&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies requirements for electromedical devices; it has more than 60 related publications, that describe very specific areas of electromedical devices.&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030287754&quot;&gt;EN 62304:2006+A1:2015&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies how to design and code software for medical devices and sets requirements for SW change control.&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q2_1 {
            get {
                return ResourceManager.GetString("Q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030157836&quot;&gt;BS EN 80001-1:2011&lt;/a&gt; and &lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030244875&quot;&gt;PD IEC/TR 80001-2-1:2012&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;And any additional chapters that may be applicable to your device and your net.&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q2_1_1 {
            get {
                return ResourceManager.GetString("Q2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/SearchResults/?q=14708&quot;&gt;ISO 14708-1:2014&lt;/a&gt; and any of the additional chapters of this standard that may be applicable to your specific device&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies requirements for all devices that are implanted in the human body and are also active; there are specific chapters for some medical devices (for example, -2 for cardiac pacemakers)&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030255136&quot;&gt;EN ISO 11607-1:2009+A1:2014&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies how the devices shall be packaged to allow sterilization and ensure that they remain sterile.&lt;/p&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///    &lt;p&gt;You may also be interested in &lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030152866&quot;&gt;ISO 14644-1&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;This standard specifies requirements for the manufacturing environments.&lt;/p&gt;
        ///    &lt;p&gt;NOTE: this standards has  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Q4_1 {
            get {
                return ResourceManager.GetString("Q4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030318543&quot;&gt;EN ISO 11135:2014&lt;/a&gt;&lt;/p&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///    &lt;p&gt;You may also be interested in &lt;a href=&quot;http://shop.bsigroup.com/ProductDetail?pid=000000000030321506&quot;&gt;EN ISO 11138-2:2017&lt;/a&gt;&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q4_1_1 {
            get {
                return ResourceManager.GetString("Q4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;https://www.iso.org/obp/ui/#iso:std:iso:11137:-1:ed-1:v1:en&quot;&gt;ISO 11137&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;Read at least chapter -1 and -2, you may also be interested in chapter -3&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q4_1_2 {
            get {
                return ResourceManager.GetString("Q4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;https://www.iso.org/obp/ui/#iso:std:iso:17665:-1:ed-1:v1:en&quot;&gt;ISO 17665-1:2006(en)&lt;/a&gt;&lt;/p&gt;
        ///    &lt;p&gt;You may also be interested in chapter -2 of this same standard&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q4_1_3 {
            get {
                return ResourceManager.GetString("Q4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;https://www.iso.org/obp/ui/#iso:std:iso:20857:ed-1:v1:en&quot;&gt;ISO 20857:2010(en)&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        public static string Q4_1_4 {
            get {
                return ResourceManager.GetString("Q4_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;a href=&quot;https://www.iso.org/obp/ui/#iso:std:iso:13408:-1:ed-2:v1:en&quot;&gt;ISO 13408-1:2008(en)&lt;/a&gt; and any of the additional chapters of this standard that may be applicable to your specific process.
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q4_2 {
            get {
                return ResourceManager.GetString("Q4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;&lt;a href=&quot;https://www.iso.org/obp/ui/#iso:std:iso:10993:-1:ed-4:v1:en&quot;&gt;ISO 10993-1&lt;/a&gt; and any of the additional chapters of this standard that may be applicable to your specific device&lt;/p&gt;
        ///    &lt;p&gt;NOTE: This standard has 18 additional chapters, reading the chapter -1 will guide you on the choice of the applicable additional chapters.&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q5 {
            get {
                return ResourceManager.GetString("Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;p&gt;ISO 22442-1:2015(en) and any of the additional chapters of this standard that may be applicable to your specific device&lt;/p&gt;
        ///    &lt;p&gt;TODO: No link...&lt;/p&gt;
        ///&lt;/li&gt;.
        /// </summary>
        public static string Q5_1 {
            get {
                return ResourceManager.GetString("Q5_1", resourceCulture);
            }
        }
    }
}
