//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubora.Domain.ApplicableRegulations.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IsoStandardTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IsoStandardTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubora.Domain.ApplicableRegulations.Texts.IsoStandardTexts", typeof(IsoStandardTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read EN ISO 14630:2012 
        ///This standard specifies requirements for all devices that are implanted in the human body but are not active. 
        ///More details at 
        ///http://shop.bsigroup.com/ProductDetail?pid=000000000030261816
        ///
        ///NOTE: his norm is closely related to EN ISO 16061: 2015 that refers to associated instruments.
        ///More details at http://shop.bsigroup.com/ProductDetail?pid=000000000030285625.
        /// </summary>
        public static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read IEC 60601-1:2005+AMD1:2012 CSV  Consolidated version
        ///
        ///This standard specifies requirements for electromedical devices; it has more than 60 related publications, that describe very specific areas of electromedical devices.
        ///More details at https://webstore.iec.ch/publication/2612.
        /// </summary>
        public static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hen read EN 62304:2006+A1:2015. This standard specifies how to design and code software for medical devices and sets requirements for SW change control.
        ///More details at http://shop.bsigroup.com/ProductDetail?pid=000000000030287754.
        /// </summary>
        public static string Q2_1 {
            get {
                return ResourceManager.GetString("Q2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read BS EN 80001-1:2011 and PD IEC/TR 80001-2-1:2012
        ///And any additional chapters that may be applicable to your device and your net
        ///http://shop.bsigroup.com/ProductDetail?pid=000000000030157836 
        ///http://shop.bsigroup.com/ProductDetail?pid=000000000030244875.
        /// </summary>
        public static string Q2_1_1 {
            get {
                return ResourceManager.GetString("Q2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 14708-1:2014 and any of the additional chapters of this standard that may be applicable to your specific device.
        ///
        ///This standard specifies requirements for all devices that are implanted in the human body and are also active; there are specific chapters for some medical devices (for example, -2 for cardiac pacemakers)
        ///More details at http://shop.bsigroup.com/SearchResults/?q=14708.
        /// </summary>
        public static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read EN ISO 11607-1:2009+A1:2014. This standard specifies how the devices shall be packaged to allow sterilization and ensure that they remain sterile. 
        ///More details at http://shop.bsigroup.com/ProductDetail?pid=000000000030255136
        ///
        ///You may also be interested in  ISO 14644-1 that specifies requirements for the manufacturing environments; NOTE: this standards has multiple chapters that may not be required while designing a medical device but will be mandatory during industrialization.
        ///http://shop.bsi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Q4_1 {
            get {
                return ResourceManager.GetString("Q4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read  EN ISO 11135:2014
        ///http://shop.bsigroup.com/ProductDetail?pid=000000000030318543 
        ///
        ///You may also be interested to EN ISO 11138-2:2017
        ///http://shop.bsigroup.com/ProductDetail?pid=000000000030321506.
        /// </summary>
        public static string Q4_1_1 {
            get {
                return ResourceManager.GetString("Q4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 11137, at least chapter -1 and -2, you may also be interested in chapter -3
        ///https://www.iso.org/obp/ui/#iso:std:iso:11137:-1:ed-1:v1:en.
        /// </summary>
        public static string Q4_1_2 {
            get {
                return ResourceManager.GetString("Q4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 17665-1:2006(en), you may also be interested in chapter -2 of this same standard.
        ///https://www.iso.org/obp/ui/#iso:std:iso:17665:-1:ed-1:v1:en.
        /// </summary>
        public static string Q4_1_3 {
            get {
                return ResourceManager.GetString("Q4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 20857:2010(en)
        ///https://www.iso.org/obp/ui/#iso:std:iso:20857:ed-1:v1:en.
        /// </summary>
        public static string Q4_1_4 {
            get {
                return ResourceManager.GetString("Q4_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 13408-1:2008(en), and any of the additional chapters of this standard that may be applicable to your specific process.
        ///https://www.iso.org/obp/ui/#iso:std:iso:13408:-1:ed-2:v1:en.
        /// </summary>
        public static string Q4_2 {
            get {
                return ResourceManager.GetString("Q4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 10993-1 and any of the additional chapters of this standard that may be applicable to your specific device https://www.iso.org/obp/ui/#iso:std:iso:10993:-1:ed-4:v1:en
        ///
        ///NOTE: This standard has 18 additional chapters, reading the chapter -1 will guide you on the choice of the applicable additional chapters..
        /// </summary>
        public static string Q5 {
            get {
                return ResourceManager.GetString("Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then read ISO 22442-1:2015(en) and any of the additional chapters of this standard that may be applicable to your specific device
        ///https://www.iso.org/obp/ui/#iso:std:iso:10993:-1:ed-4:v1:en.
        /// </summary>
        public static string Q5_1 {
            get {
                return ResourceManager.GetString("Q5_1", resourceCulture);
            }
        }
    }
}
